### ISSUE TITLE
No sound or notification?

### ISSUE THREAD

**Issue by cpohli** [clemstation/privacy-policies#2]
A brilliant idea to program a timer!
I just installed it via the Appstore on my Mac and it's working fine, except i get no sounds or notification, when the timer is up?
it's all enabled under system settings/notifications on the Mac (Sequoia 15.0.1, MacMini M1).

**Comment by clemstation** [comment]
Yes I'm aware of the sound issue. I'm hoping to come up with a fix by end of week.
Also the notifications are coming soon!
Thank you so much for taking the time to provide feedback.

**Comment by clemstation** [comment]
Hi there,

Version 1.3 is available on the App Store and should fix the issue ☺️.

Thanks for your patience!

Clement
@clemstation

**Comment by clemstation** [comment]
Version 1.3 is available on the App Store and should fix the issue ☺️.

Thanks for your patience!

**Comment by diva-D** [comment]
Nice work! Much more useful now that I can tell when its finished.

**Comment by cpohli** [comment]
Ah, great. Working perfect. 
Thanks again for making this little piece of helpful, not bloated and clean designed tool!
